name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache node modules
      # This step caches the node_modules based on package-lock.json
        uses: actions/cache@v3
        # Cache node modules
        with: 
          # Specify the cache   
          path: node_modules
          # key means unique identifier for the cache
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache node modules
      # This step caches the node_modules based on package-lock.json
        uses: actions/cache@v3
        # Cache node modules
        with: 
          # Specify the cache   
          path: node_modules
          # key means unique identifier for the cache
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist

  read-file-name-and-publish:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      js-file-name: ${{ steps.publish-js-file.outputs.file_name }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: dist

      - name: Publish JS file name
        id: publish-js-file
        run: |
          FILE_NAME=$(find dist/assets -name "*.js" -type f | head -n 1)
          echo "Found JS file: $FILE_NAME"
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT

  deploy:
    needs: [build, read-file-name-and-publish]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: dist

      - name: List files
        run: ls -la dist/assets

      - name: Output JS file name
        run: echo "The JS file is ${{ needs.read-file-name-and-publish.outputs.js-file-name }}"

      - name: Deploy
        run: echo "Deploying..."
